version: "3.8"

services:
  db_cont:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: raildb
    volumes:
      - db_data:/var/lib/mysql

  serv_cont:
    image: rails-img
    ports:
      - "8080:3000"
    depends_on:
      - db_cont
    environment:
      DB_HOST: db_cont
      DB_USER: root
      DB_PASSWORD: pswd
      DB_NAME: raildb

volumes:
  db_data:

