version: "3.8"

services:
  db_cont:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: raildb
    volumes:
      - db_data:/var/lib/mysql

  serv_cont:
    image: rails-img
    depends_on:
      - db_cont
    environment:
      DB_HOST:
      DB_USER:
      DB_PASSWORD:
      DB_NAME:

  nginx_cont:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - serv_cont


volumes:
  db_data:

